### PR TITLE
Add cookie consent banner

### LINKED ISSUE #226: Cookie consent
As we use cookies on the site, we should at least provide a consent box for the user to agree.

### PR DESCRIPTION
**Pull request by as3810t**
This pull request adds a cookie consent banner to the site. Unless the user consents to cookies:

- The social plugins will be blocked from loading
- The language selector will not store the user preferences

### CODE REVIEW

**Review by triszt4n — APPROVED** [review]
Very nicely written code, works fine on all viewports 💯 

(Just saw the deploy workflow change, nice catch!)

**Comment by as3810t** [comment]
Thanks! I am trying to reintegrate netlify for staging. I also had to modify the GH workflow, as it was deploying everything to gh-pages (now it only deploys master).

**Comment by as3810t** [comment]
@micskeiz @marci543 
I added a cookie banner to the site. Please review if the implemented banner meets your expectations.

> :sunglasses: Browse the preview: https://deploy-preview-237--affectionate-kirch-09fac8.netlify.app/

**Review by marci543 — APPROVED** [review]
LGTM

**Comment by micskeiz** [comment]
Nice, thanks! I like handling the Decline button.

**Pull request merged**
