### PR TITLE
Fix scrolling issue

### LINKED ISSUE #210: Overlapping navbars after scrolling
Steps to reproduce (approximately):
- move mouse out of the window (optional)
- press `End` to scroll down
- wait a few seconds (optional)
- press (and optionally hold) `Home` to scroll up
- if bug is not present, try again

Expected faulty behaviour: upper navbar covers the lower one

Screenshot:
image

Platform: Firefox 91 or Chrome 93, Windows 10

### PR DESCRIPTION
**Pull request by as3810t**
This PR fixes #210.

### CODE REVIEW

**Comment by as3810t** [comment]
@marci543 Please check whether the issue still persists. On my devices the issue has been resolved. The cause was that the scroll event listener did not fire fast enough if you scrolled up rapidly.

**Comment by marci543** [comment]
I cannot reproduce the issue. It seems to be fixed. Thanks.

**Comment by marci543** [comment]
Although there are two new grey bars below the navbars. They become white if I accept the cookies.
comparison

**Comment by as3810t** [comment]
@marci543 The gray bar issue should be fixed now. Can you please check again?

**Comment by marci543** [comment]
The grey bar is gone. Thanks.

**Pull request merged**
